version: '3'

services: 

    postgres:
        image: postgres:10-alpine
        env_file: .env
        ports:
            - 5432:5432
        volumes:
            - ./data:/var/lib/postgresql/data
        networks:
            - default
    
    admin:
        image: adminer
        ports:
        - 8088:8080

networks:
    default:
        driver: bridge