# Generated by Django 4.0.2 on 2022-02-28 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customuser',
            table='member',
        ),
    ]
