# Generated by Django 4.0.2 on 2022-03-01 14:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_vehicle_member_created_member_updated_usevehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teasurer',
            fields=[
                ('member_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.member')),
                ('canWithDraw', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'teasurer',
            },
            bases=('core.member',),
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=200)),
                ('destiny', models.CharField(max_length=200)),
                ('startDate', models.DateTimeField(default=datetime.datetime.now)),
                ('endDate', models.DateTimeField(null=True)),
                ('kilometer', models.FloatField()),
                ('created', models.DateTimeField(default=datetime.datetime.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vehicle')),
            ],
            options={
                'db_table': 'trip',
            },
        ),
    ]
