# Generated by Django 4.0.2 on 2022-03-01 15:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_member_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='created',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='updated',
            new_name='updatedAt',
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='created',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='updated',
            new_name='updatedAt',
        ),
        migrations.RenameField(
            model_name='usevehicle',
            old_name='created',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='created',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='updated',
            new_name='updatedAt',
        ),
        migrations.RemoveField(
            model_name='usevehicle',
            name='updated',
        ),
        migrations.AddField(
            model_name='cashier',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='cashier',
            name='deletedAt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='cashier',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='member',
            name='deletedAt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='deletedAt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='usevehicle',
            name='deletedAt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='usevehicle',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='deletedAt',
            field=models.DateTimeField(null=True),
        ),
    ]
