# Generated by Django 4.0.2 on 2022-03-01 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_created_member_createdat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('member_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.member')),
                ('canWithDraw', models.BooleanField(default=False)),
                ('canUseVehicle', models.BooleanField(default=False)),
                ('montlyValue', models.FloatField()),
            ],
            options={
                'db_table': 'partner',
            },
            bases=('core.member',),
        ),
    ]
