# Generated by Django 4.0.2 on 2022-03-01 19:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_partner'),
    ]

    operations = [
        migrations.CreateModel(
            name='President',
            fields=[
                ('member_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.member')),
                ('startMandate', models.DateTimeField(default=datetime.datetime.now)),
                ('endMandate', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'president',
            },
            bases=('core.member',),
        ),
        migrations.RemoveField(
            model_name='partner',
            name='canWithDraw',
        ),
        migrations.AddField(
            model_name='member',
            name='vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.vehicle'),
        ),
        migrations.AddField(
            model_name='partner',
            name='message',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(default=datetime.datetime.now)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('deletedAt', models.DateTimeField(null=True)),
                ('message', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('CONCLUDED', 'Concluído'), ('PENDING', 'Pendente'), ('REFUSED', 'Recusado')], max_length=9)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.partner')),
                ('president', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.president')),
            ],
            options={
                'db_table': 'request',
            },
        ),
        migrations.CreateModel(
            name='MontlyPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(default=datetime.datetime.now)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('deletedAt', models.DateTimeField(null=True)),
                ('paymenDate', models.DateTimeField(default=datetime.datetime.now)),
                ('dueDate', models.DateTimeField(null=True)),
                ('value', models.FloatField()),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.partner')),
            ],
            options={
                'db_table': 'montly_payment',
            },
        ),
        migrations.CreateModel(
            name='Justification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(default=datetime.datetime.now)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('deletedAt', models.DateTimeField(null=True)),
                ('message', models.CharField(max_length=200)),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.member')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vehicle')),
            ],
            options={
                'db_table': 'justification',
            },
        ),
        migrations.CreateModel(
            name='Demand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(default=datetime.datetime.now)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('deletedAt', models.DateTimeField(null=True)),
                ('message', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('CONCLUDED', 'Concluded'), ('PENDING', 'Pendente'), ('REFUSED', 'Recusado')], max_length=9)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.partner')),
                ('teasurer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.teasurer')),
            ],
            options={
                'db_table': 'demand',
            },
        ),
    ]
