# Generated by Django 4.0.2 on 2022-03-01 19:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_president_remove_partner_canwithdraw_member_vehicle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(default=datetime.datetime.now)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('deletedAt', models.DateTimeField(null=True)),
                ('justification', models.CharField(max_length=200)),
                ('value', models.FloatField()),
                ('type', models.CharField(choices=[('OUT', 'Retirada'), ('IN', 'Entrada')], max_length=3)),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cashier')),
                ('teasurer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.teasurer')),
            ],
            options={
                'db_table': 'financial_transacrtion',
            },
        ),
    ]
